# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c4a215f13c4decd10d45461c323b2f247108cbe57df2abc48d467c79483f52a0966937a626c78075d72fea1cfc2ba7956150d6eea2f3aad4ade2e1c1d097afc9

test:
  secret_key_base: 930ae396376c7d42c604eadd0ed89f08cf9fab0c65d9428d69850be28dd16ae472f0092450d3954b24d9d700fe92e509e9c87b042bbff6ae15cbaaf142cd09a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
